### ISSUE TITLE
"invalid grant" during transport Exchange call

### ISSUE THREAD

**Issue by booyaa** [pnelson/moves#3]
According to the authorization documentation:

> invalid_grant: the provided authorization code is not valid, has been revoked or has expired (after 5 minutes). Note that both successful and unsuccessful requests revoke the code. Also check that the redirect_uri parameter is included if necessary.

I was able to get my 8 digit authorization code now that I have a Request URI defined, when I enter it into my app. I get the `invalid grant` error during the `token, err := t.Exchange(code)`.

I added debug line in the transport's Exchange func to dump the query string, which looked good to me (see below) 

`map[grant_type:[authorization_code] code:[21416819] client_id:[*****] client_secret:[******]]`

I'm wondering what else I might have missed? I'm always using a new authorization code because I know this code is revoked after successful or failed call.

Here's my reference code: https://github.com/booyaa/dthulhu/blob/master/plugins/moves.go

As you can see it's almost identical to your own reference code.

**Comment by pnelson** [comment]
I think I understand what is happening. You don't actually need a new authorization code every time. The example I provided is actually a poor example of real world usage. It is just there to show the full flow.

When you run through the full flow, you will notice it creates a `token_cache` file by default. This package allows you to switch the cache backend to some other persistent store later. Anyway, at this point you've exchanged that 8 digit authorization code for an OAuth access token. That is what you need to perform subsequent valid API requests.

Going back to your example. If you start fresh by revoking the Moves app and deleting the `token_cache` file and just run through the flow once again. Now you have a fresh `token_cache` file.

Now let's say you want to perform another API call. You can skip the OAuth dance entirely. You can comment out everything between `t := &moves.Transport{...}` and `api := t.Client()` and continue to perform requests because your access token gets picked up from the `TokenCache`.

I created a gist of your code to demonstrate:
https://gist.github.com/pnelson/5714d8c946a153baf1bc

Additionally, your access token will expire after a few hours. This package should detect when your access token is expired and use the refresh token (also stored in your token cache) to seamlessly create an updated access token.

**Comment by booyaa** [comment]
Thanks for getting back to me, I think I'm not even getting far as getting a token. If I was successful there would be a file called token_cache?

Can I confirm the authorisation flow? I'm fairly new to oauth, and my other APIs have been able to provide a personal access token without the oauth handshake:

Setup
1. Create an app on dev.moves-app.com
2. Setup a redirect url (does this need to point back to my app?)
3. Copy client id and secret

Run my app
1. my app provides an authorisation url
2. copy the pin and paste into the console running my app
3. get token as part of the transport Exchange func call (your library will cache it)
4. do something with the api i.e. get storyline
5. my app exits

If these steps are correct then I fail at step 3 of Run my app. The Exchange fails with invalid_grant error.

**Comment by pnelson** [comment]
Yeah, the `token_cache` file is generated in `Exchange` so if you are failing there then that explains why the file doesn't get generated.

Setup instructions sound good. Yes, the **Redirect URI** should point to your app if you want to complete the authorization flow with minimal human interaction. See steps 3 and 4 below. Your HTTP handler for **Redirect URI** can take care if that instead of manually copy/pasting as in the example.

I just ran through the authorization flow myself and documented the steps I encountered.
1. Provide an authorization/login URL. (ex. https://api.moves-app.com/oauth/v1/authorize?client_id=mfWQ32X0_7pB2b6P7Ue1ZWio0Swz4J4O&response_type=code&scope=activity+location&state=foo)
2. Enter 8 digit PIN from authorization URL to mobile app and 'Allow' access.
3. Authorization page redirects to the **Redirect URI** (a handler within your app) with a `code` query parameter. (ex. http://localhost:3000/?code=**TBO1XR33KppVRKAggU7p2SNoDBY4OlWdG0OX3Z1T9AZH7v879r9Xck2074f7z0ru**&state=foo)
4. Exchange the code (bolded in previous step) for an **access token**.
5. Do something with the API. (ex. get storyline)

Once you get past step 4, you will have your token (and the `token_cache` file) and should be able to continue making API requests without needing to go through steps 1-4 again until your token expires.

**Comment by booyaa** [comment]
:dancers: Yes! We have a token! 

So a combination of my using a webserver that I wrote for another project that didn't echo back the whole incoming URL (from the Moves Redirect URI including the important `code` field) and not understanding that the `code` I was meant to enter was not the pin caused all these problems.

Thanks again for your help on this and the last issue!
